// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingIntel.Infrastructure.Persistence;

#nullable disable

namespace TradingIntel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradingIntelDbContext))]
    [Migration("20260423034642_AddTradeOpportunities")]
    partial class AddTradeOpportunities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TradingIntel.Infrastructure.Persistence.Entities.MarketListingSnapshotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BuyNowPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ListingId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StartingBid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_market_listing_snapshots_listing_id");

                    b.HasIndex("PlayerId", "CapturedAtUtc")
                        .HasDatabaseName("ix_market_listing_snapshots_player_captured_at");

                    b.ToTable("market_listing_snapshots", (string)null);
                });

            modelBuilder.Entity("TradingIntel.Infrastructure.Persistence.Entities.PlayerPriceSnapshotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BuyNowPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MedianMarketPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SellNowPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "CapturedAtUtc")
                        .HasDatabaseName("ix_player_price_snapshots_player_captured_at");

                    b.HasIndex("Source", "CapturedAtUtc")
                        .HasDatabaseName("ix_player_price_snapshots_source_captured_at");

                    b.ToTable("player_price_snapshots", (string)null);
                });

            modelBuilder.Entity("TradingIntel.Infrastructure.Persistence.Entities.RawSnapshotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PayloadHash")
                        .HasDatabaseName("ix_raw_snapshots_payload_hash");

                    b.HasIndex("Source", "CapturedAtUtc")
                        .HasDatabaseName("ix_raw_snapshots_source_captured_at");

                    b.ToTable("raw_snapshots", (string)null);
                });

            modelBuilder.Entity("TradingIntel.Infrastructure.Persistence.Entities.SbcChallengeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepeatabilityKind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RepeatabilityMaxCompletions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_sbc_challenges_category");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_sbc_challenges_expires_at");

                    b.ToTable("sbc_challenges", (string)null);
                });

            modelBuilder.Entity("TradingIntel.Infrastructure.Persistence.Entities.SbcChallengeRequirementRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Maximum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minimum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId")
                        .HasDatabaseName("ix_sbc_challenge_requirements_challenge_id");

                    b.HasIndex("Key", "Minimum")
                        .HasDatabaseName("ix_sbc_challenge_requirements_key_minimum");

                    b.ToTable("sbc_challenge_requirements", (string)null);
                });

            modelBuilder.Entity("TradingIntel.Infrastructure.Persistence.Entities.TradeOpportunityRecord", b =>
                {
                    b.Property<long>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedBuyPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedSellPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStale")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastRecomputedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.HasIndex("IsStale")
                        .HasDatabaseName("ix_trade_opportunities_is_stale");

                    b.HasIndex("LastRecomputedAtUtc")
                        .HasDatabaseName("ix_trade_opportunities_last_recomputed");

                    b.ToTable("trade_opportunities", (string)null);
                });

            modelBuilder.Entity("TradingIntel.Infrastructure.Persistence.Entities.SbcChallengeRequirementRecord", b =>
                {
                    b.HasOne("TradingIntel.Infrastructure.Persistence.Entities.SbcChallengeRecord", "Challenge")
                        .WithMany("Requirements")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");
                });

            modelBuilder.Entity("TradingIntel.Infrastructure.Persistence.Entities.SbcChallengeRecord", b =>
                {
                    b.Navigation("Requirements");
                });
#pragma warning restore 612, 618
        }
    }
}
