// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingIntel.Infrastructure.Persistence;

#nullable disable

namespace TradingIntel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradingIntelDbContext))]
    [Migration("20260423015118_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TradingIntel.Infrastructure.Persistence.Entities.MarketListingSnapshotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BuyNowPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ListingId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StartingBid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_market_listing_snapshots_listing_id");

                    b.HasIndex("PlayerId", "CapturedAtUtc")
                        .HasDatabaseName("ix_market_listing_snapshots_player_captured_at");

                    b.ToTable("market_listing_snapshots", (string)null);
                });

            modelBuilder.Entity("TradingIntel.Infrastructure.Persistence.Entities.PlayerPriceSnapshotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BuyNowPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MedianMarketPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerDisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SellNowPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "CapturedAtUtc")
                        .HasDatabaseName("ix_player_price_snapshots_player_captured_at");

                    b.HasIndex("Source", "CapturedAtUtc")
                        .HasDatabaseName("ix_player_price_snapshots_source_captured_at");

                    b.ToTable("player_price_snapshots", (string)null);
                });

            modelBuilder.Entity("TradingIntel.Infrastructure.Persistence.Entities.RawSnapshotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PayloadHash")
                        .HasDatabaseName("ix_raw_snapshots_payload_hash");

                    b.HasIndex("Source", "CapturedAtUtc")
                        .HasDatabaseName("ix_raw_snapshots_source_captured_at");

                    b.ToTable("raw_snapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
